@baseUrl = http://localhost:3001
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc4NDUzMDk0OSwiZXhwIjoxNzg0NTM0NTQ5fQ.Ljixh03Jygo18sMO79Wyc4vARiKySwQ3APzYX1ogSak

### 내 정보 조회
GET {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}

### 내 보유 카드 목록 조회
GET {{baseUrl}}/users/me/inventories
Authorization: Bearer {{accessToken}}

### 내가 제시한 교환 목록 조회
GET {{baseUrl}}/users/me/exchange-proposals
Authorization: Bearer {{accessToken}}

### 나의 판매 포토카드 목록 조회
GET {{baseUrl}}/users/me/market-postings
Authorization: Bearer {{accessToken}}


### 알림 목록 조회
GET {{baseUrl}}/users/me/notifications
Authorization: Bearer {{accessToken}}

### 알림 목록 조회 - 토큰 제거 ver
GET {{baseUrl}}/users/me/notifications